# Generated by Django 4.2.3 on 2023-10-20 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_admin_password_alter_admin_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '临时')], default=3, verbose_name='程度')),
                ('title', models.CharField(max_length=64, verbose_name='题目')),
                ('detail', models.TextField(verbose_name='细节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin', verbose_name='负责人')),
            ],
        ),
    ]
