# Generated by Django 4.2.3 on 2023-10-31 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64, verbose_name='订单号')),
                ('title', models.CharField(max_length=64, verbose_name='商品名')),
                ('price', models.CharField(max_length=64, verbose_name='价格')),
                ('status_choice', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], verbose_name='支付状态')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin', verbose_name='管理员')),
            ],
        ),
    ]
