# Generated by Django 4.2.3 on 2023-11-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_choice',
            new_name='status',
        ),
    ]
